image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - release

variables:
  CONTAINER_TEST_IMAGE: isciences/exactextract:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: isciences/exactextract:latest

.unittest_template: &unittest_definition
  script:
    - geos-config --version
    - mkdir build-coverage
    - cd build-coverage
    - cmake -DCMAKE_BUILD_TYPE=Coverage -DBUILD_CLI=NO -DBUILD_PYTHON=NO ..
    - make -j2 catch_tests
    - valgrind --leak-check=full --error-exitcode=1 ./catch_tests
  after_script:
    - cd build-coverage
    - lcov --capture --directory CMakeFiles --output-file coverage.info
    - bash <(curl -s https://codecov.io/bash)

test:geos35:
  stage: test
  image: isciences/exactextract-test-env:geos35
  <<: *unittest_definition
  
test:geos36:
  stage: test
  image: isciences/exactextract-test-env:geos36
  <<: *unittest_definition
  
test:geos37:
  stage: test
  image: isciences/exactextract-test-env:geos37
  <<: *unittest_definition

test:geos38:
  stage: test
  image: isciences/exactextract-test-env:geos38
  <<: *unittest_definition

test:geos39:
  stage: test
  image: isciences/exactextract-test-env:geos39
  <<: *unittest_definition

test:geos310:
  stage: test
  image: isciences/exactextract-test-env:geos310
  <<: *unittest_definition

test:geos311:
  stage: test
  image: isciences/exactextract-test-env:geos311
  <<: *unittest_definition

test:geos312:
  stage: test
  image: isciences/exactextract-test-env:geos312
  <<: *unittest_definition

test:cli:
  stage: test
  image: isciences/exactextract-test-env:geos312
  script:
    - geos-config --version
    - mkdir build-coverage
    - cd build-coverage
    - cmake -DCMAKE_BUILD_TYPE=Coverage -DBUILD_CLI=YES -DBUILD_PYTHON=NO ..
    - make -j2 exactextract_bin subdivide
    - pytest ../test
  after_script:
    - cd build-coverage
    - lcov --capture --directory CMakeFiles --output-file coverage.info
    - bash <(curl -s https://codecov.io/bash)

test:python:
  stage: test
  image: isciences/exactextract-test-env:geos312
  script:
    - apt-get install -y python3-dev pybind11-dev
    - geos-config --version
    - mkdir build-coverage
    - cd build-coverage
    - cmake -DCMAKE_BUILD_TYPE=Coverage -DBUILD_CLI=NO -DBUILD_PYTHON=YES ..
    - cmake --build . -j2
    - ctest -R pybindings --output-on-failure
  after_script:
    - cd build-coverage
    - lcov --capture --directory CMakeFiles --output-file coverage.info
    - bash <(curl -s https://codecov.io/bash)

build:
  stage: build
  script:
    - docker login -u ci4isciences -p $DOCKERHUB_PW
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - master

pages:
  stage: release
  image: isciences/exactextract-build-env:latest
  script:
    - mkdir build-docs
    - cd build-docs
    - cmake -DBUILD_CLI=NO ..
    - make doc_doxygen
    - mv html ../public
  artifacts:
    paths:
      - public
  only:
    - master

release-image:
  stage: release
  script:
    - docker login -u ci4isciences -p $DOCKERHUB_PW
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE

  only:
    - master

