test-stable:
        image: isciences/exactextract-build-env:stable
        script:
                - mkdir build-master
                - cd build-master
                - cmake ..
                - make catch_tests
                - ./catch_tests

test-geos37:
        image: isciences/exactextract-build-env:geos37
        script:
                - mkdir build-master
                - cd build-master
                - cmake ..
                - make catch_tests
                - ./catch_tests

