test-latest:
  image: rocker/geospatial:latest
  script:
    - R -e "devtools::document()"
    - R -e "devtools::check()"

test-devel:
  image: rocker/geospatial:devel
  script:
    - R -e "devtools::document()"
    - R -e "devtools::check()"
