test-latest:
  image: rocker/geospatial:latest
  script:
    - R -e "devtools::document()"
    - R CMD build . --no-build-vignettes --no-manual
    - export PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran

test-devel:
  image: rocker/geospatial:devel
  script:
    - R -e "devtools::document()"
    - R CMD build . --no-build-vignettes --no-manual
    - export PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran
