name: Python package build

on:
  - push
  - pull_request


defaults:
  run:
    shell: bash -l {0}

jobs:

  build:
    name: Build ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: .github/python_test_env.yml

    - name: Build wheel
      working-directory: ./python
      run: pip wheel . -v

    - name: Install wheel
      working-directory: ./python
      run: pip install exactextract*.whl

    - name: Test
      run: pytest python/tests

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-py${{ matrix.python-version }}
        path: ./python/*.whl
        if-no-files-found: error

    - name: Build source distribution
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
      working-directory: ./python 
      run: python setup.py sdist

    - name: Upload source distribution(s)
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: ./python/dist/*
        if-no-files-found: error
